### ISSUE TITLE
Ability to customize monolog

### ISSUE THREAD

**Issue by ozanhazer** [lavary/crunz#216]
It would be quite flexible if we could inject our own monolog instance or configure it somehow.

For example I'd prefer to use RotatingFileHandler to log the outputs and errors. The log files can get too large after some time and I'd prefer doing the rotation at the application level instead of configuring the logrotated in every server.

Also it would be easier to collect logs in a 3rd party service in a multi-server setup. Or errors can be sent to slack etc. a lot of options there...

**Comment by PabloKowalczyk** [comment]
Hello, i like your idea.
Passing configured Monolog instance per task can be useful in some cases but IMO it will be much better, for most users, to configure it once for all tasks.
Would you like to provide a PR for this?

**Comment by ozanhazer** [comment]
I would... I'm not sure how to do it through the yaml file though, any suggestions on that?

**Comment by PabloKowalczyk** [comment]
You mean how to add new configuration options for Crunz?

**Comment by ozanhazer** [comment]
I think I can figure that out from the source code but I'm not sure how and where the consumer (the programmer using crunz) should define the instance.

Consider the following code from monolog's documentation:

```
use Monolog\Logger;
use Monolog\Handler\StreamHandler;

// create a log channel
$log = new Logger('name');
$log->pushHandler(new StreamHandler('path/to/your.log', Logger::WARNING));
```

How's crunz going to be aware of `$log`? What do I write to the config?

```
monolog_factory: 
  file: src/CrunzLogFactory.php
  class: \MyApp\CrunzLogFactory
```

maybe and the `CrunzLogFactory` would have an `__invoke` method to build the instance.

**Comment by PabloKowalczyk** [comment]
I see now, sorry for misunderstanding. IMO Symfony done great job with `MonologBundle` (https://symfony.com/doc/current/logging.html#handlers-writing-logs-to-different-locations), maybe this can be a reference design?
Example config:
```
# crunz.yml
monolog:
    handlers:
        # this "file_log" key could be anything
        file_log:
            type: stream
            # log to var/log/(environment).log
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            # log *all* messages (debug is lowest level)
            level: debug

        syslog_handler:
            type: syslog
            # log error-level messages and higher
            level: error
```
Under the hood some `MonologFactory` should read `type` from handler and init appropriate class - again, Symfony implementation can be a reference.
Of course there is no need to add every possible `type` for the start, one or two will be enough IMO.
WDYT?
